    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    panda_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - panda_joint1
            - panda_joint2
            - panda_joint3
            - panda_joint4
            - panda_joint5
            - panda_joint6
            - panda_joint7

        constraints:
            goal_time: 10.0
            stopped_velocity_tolerance: 0.05
            panda_joint1: {trajectory: 0.1, goal: 0.1}
            panda_joint2: {trajectory: 0.1, goal: 0.1}
            panda_joint3: {trajectory: 0.1, goal: 0.1}
            panda_joint4: {trajectory: 0.1, goal: 0.1}
            panda_joint5: {trajectory: 0.1, goal: 0.1}
            panda_joint6: {trajectory: 0.1, goal: 0.1}
            panda_joint7: {trajectory: 0.1, goal: 0.1}

        gains:
            panda_joint1: {p: 1000, d: 500, i: 0, i_clamp: 1}
            panda_joint2: {p: 1000, d: 150, i: 0, i_clamp: 1}
            panda_joint3: {p: 5000, d: 150, i: 10, i_clamp: 50}
            panda_joint4: {p: 5000, d: 150, i: 1, i_clamp: 25}
            panda_joint5: {p: 1000, d: 50, i: 0, i_clamp: 1}
            panda_joint6: {p: 1000, d: 20, i: 0, i_clamp: 1}
            panda_joint7: {p: 1000, d: 10, i: 0, i_clamp: 1}
        stop_trajectory_duration: 0.5
        state_publish_rate:  25
        action_monitor_rate: 10

    panda_hand_controller:
       type: effort_controllers/JointTrajectoryController
       joints:
            - panda_finger_joint1
            - panda_finger_joint2

       constraints:
            goal_time: 3.0
            stopped_velocity_tolerance: 0.05
            panda_finger_joint1: {trajectory: 0.1, goal: 0.02}
            panda_finger_joint2: {trajectory: 0.1, goal: 0.02}
       gains:
            panda_finger_joint1: {p: 100000, d: 100, i: 1, i_clamp: 1}
            panda_finger_joint2: {p: 100000, d: 100, i: 1, i_clamp: 1}
       stop_trajectory_duration: 0.5
       state_publish_rate:  25
       action_monitor_rate: 10


      
        

