sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /grasping/cloud_snapshot
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.001
    padding_scale: 0.5
    max_update_rate: 2.0
    filtered_cloud_topic: filtered_cloud
